post http://localhost:5000/api/auth/register
content-type: application/json

{
    "nickname": "asfqw",
    "email":"example@qwerty.com",
    "password":"df"
}
###


post http://localhost:5000/api/auth/register
content-type: application/json

{
    "nickname": "asfqw",
    "email":"example@qwerty.com",
    "password":"dD1@dasdf",
    "_id": "1"
}
###

# reset users db
get http://localhost:5000/api/auth/reset
###


post http://localhost:5000/api/auth/login
content-type: application/json

{
    "email":"example@qwerty.com",
    "password":"dD1@dasdf",
    "asf":1
}
###

post http://localhost:5000/api/auth/login
content-type: application/json

{
    "emil":"example@qwerty.com",
    "pasword":"dD1@dasdf",
    "asf":1
}
###



post http://localhost:5000/api/auth/register
content-type: application/json

{
    "nickname": "asfqw"
}
###

# check middleware
get http://localhost:5000/api/auth
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.YXNmcXc.EXRL8FFr7w3S6MZBVHBDWWZFF3QxjnU1wMsGjZF3Lao
###